### ISSUE TITLE
Metadata API changes - umbrella issue

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/scylla-rust-driver#1010]
This is an umbrella issue to group all changes regarding the metadata API.

```[tasklist]
### Tasks
- [ ] Split necessary and optional metadata, fetch only necessary by default: https://github.com/scylladb/scylla-rust-driver/issues/595
- [ ] Metadata is not refreshed on SchemaChange event: https://github.com/scylladb/scylla-rust-driver/issues/546
- [ ] Make sure fetched metadata is consistent: https://github.com/scylladb/scylla-rust-driver/issues/1009
- [ ] Don't fetch metadata periodically: https://github.com/scylladb/scylla-rust-driver/issues/1008
- [ ] Add timeouts to metadata fetch: https://github.com/scylladb/scylla-rust-driver/issues/661
- [ ] Above changes allow us to close https://github.com/scylladb/scylla-rust-driver/issues/786
```
