### ISSUE TITLE
Request execution API changes - umbrella issue

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#978]
This is an umbrella issue to group all changes regarding the request execution API, as there are a number of them planned before the API gets stable.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylla-rust-driver/issues/713 - we're currently planning to implement the `Executable` trait
- [ ] https://github.com/scylladb/scylla-rust-driver/issues/262 - necessarily consider this when implementing `Executable`
- [ ] https://github.com/scylladb/scylla-rust-driver/issues/417 - this needs to be resolved if we decide to forbid executing unprepared requests with values (which we want to, in order to make requests type-safe)
- [ ] #940 - covered by `Executable`
- [ ] #941 - solves multiple issues, e.g. #974
- [ ] #108 - possibly solved by #941
```
